name: SScript

on:
  push:
  schedule:
    - cron: '0 0,8,12,21,23 * * *'
 
jobs:
  bot:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout codes'
        uses: actions/checkout@v1
      - name: 'Get Wakeup'
        run: bash ./wakeup.sh
      - name: 'Get Date'
        run: echo "REPORT_DATE=$(TZ=':Asia/Shanghai' date '+%Y-%m-%d %T')" >> $GITHUB_ENV

 
